var error_Number_One="Error: Division by Zero!",leftSide="",rightSide="",binaryOperator="",lastOperator="",lastRightSide="",canClear=!1,nextEnterIsFake=!1,complexOp="",complexIsRight=!1,isDegrees=!1,isPercent=!1;
function memPlus(a){unaryPreprocessor();var b="0",c="0";""!=document.getElementById("display1").value&&(b=document.getElementById("display1").value);""!=document.getElementById("memC").value&&(c=document.getElementById("memC").value);c=new BigDecimal(c);b=new BigDecimal(b);var e=new MathContext(40);c=1==a?c.subtract(b,e).toString():c.add(b,e).toString();$("#memC").val(c)}function memClear(){$("#memC").val("")}function memoryRecall(){$("#display1").val($("#memC").val());dc()}
function scrollHistory(){var a=$("#history1").val();if(42<a.length){var b=a.length-42;$("#history1").val(a.substr(b,a.length))}}function addToHistory(a){a=$("#history1").val()+a;$("#history1").val(a);scrollHistory()}function clearAll(a){a.value="0";binaryOperator=rightSide=leftSide="";$("#history1").val("");lastRightSide=lastOperator="";dc()}
function copyToClipboard(){var a=document.getElementById("display1");buffer=document.getElementById("display123");buffer.value=a.value;curr=buffer.value;s=buffer.value.slice(-3);if(" + "==s||" - "==s||" * "==s||" / "==s)buffer.value=buffer.value.slice(0,buffer.value.length-3);d=buffer.value;if(-1!=d.search(" - ")||-1!=d.search(" + ")||-1!=d.search(" * ")||-1!=d.search(" / "))enterPressed(),buffer.value=curr=document.getElementById("display1").value;buffer.select();document.execCommand("copy",!1,null);
buffer.value=curr;a.value=buffer.value;dc()}
function pasteFromClipboard(){var a=document.getElementById("display1");saved_on_err=a.value;buffer=document.getElementById("display123");buffer.readOnly=!1;a.readOnly=!1;buffer.value=a.value;curr="";s=buffer.value.slice(-3);if(" + "==s||" - "==s||" * "==s||" / "==s)curr=buffer.value;buffer.select();document.execCommand("paste",!1,null);curr+=buffer.value;isNumber(buffer.value)?(buffer.value=curr,a.value=buffer.value):(errorFlash(),buffer.value=saved_on_err);dc();buffer.readOnly=!0;a.readOnly=!0}
function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}function formatNumber(a){x=(a+"").split(".");x1=x[0];x2=1<x.length?"."+x[1]:"";for(a=/(\d+)(\d{3})/;a.test(x1);)x1=x1.replace(a,"$1,$2");return x1+x2}function removeZeroes(a){if("string"!=typeof a)return a;a=a.replace(/(\.[0-9]*?)0+$/,"$1");return a=a.replace(/\.$/,"")}function isInteger(a){return void 0===a||null===a?!1:0==a%1}
function dc(){var a=document.getElementById("display1"),b=document.getElementById("display123");a=a.value;s=a.slice(-3);" + "==s||" - "==s||" * "==s||" / "==s?(a=a.slice(0,a.length-3),b.value=formatNumber(a)+s):(plus=a.search(" - "),minus=a.search(" + "),divide=a.search(" / "),multiple=a.search(" * "),-1!=plus||-1!=minus||-1!=divide||-1!=multiple?(-1<plus&&(op=plus),-1<minus&&(op=minus),-1<divide&&(op=divide),-1<multiple&&(op=multiple),left=a.slice(0,op),operation=a.slice(op,a.length),right=operation.slice(3,
operation.length),operation=operation.slice(0,3),b.value=formatNumber(left)+operation+formatNumber(right)):b.value=formatNumber(a))}origin="";function errorFlash(){origin=document.getElementById("display123").style.backgroundColor;document.getElementById("display123").style.backgroundColor="red";setTimeout(backit,100)}function backit(){document.getElementById("display123").style.backgroundColor=origin;clearTimeout(this)}
function addNow(a){binaryOperator=" "+a+" ";addBinaryOp();canClear=!1;lastOperator="";dc()}
function addBinaryOp(){var a=$("#display1").val();var b=a.search(" + ");if("-1"!=b)var c=" + ";else b=a.search(" - "),"-1"!=b?c=" - ":(b=a.search(" * "),"-1"!=b?c=" * ":(b=a.search(" / "),c="-1"!=b?" / ":""));""==c?$("#display1").val(a+binaryOperator):(b=a.substring(0,b),b+=binaryOperator,b.length!=a.length&&(a=binaryOperator,enterPressed(),binaryOperator=a,b=$("#display1").val()+binaryOperator),$("#display1").val(b));dc()}
function compute(){var a=isPercent;isPercent=!1;""==leftSide&&(leftSide="0");if(" / "==binaryOperator){if(""==rightSide||0==rightSide){errorFlash();$("#display1").val(leftSide);dc();return}}else""==rightSide&&(rightSide="0");var b=new BigDecimal(leftSide),c=new BigDecimal(rightSide),e=new MathContext(40);if(a){new BigDecimal("0");a=new BigDecimal(rightSide);c=new BigDecimal(leftSide);var f=new BigDecimal("100");e=new MathContext(40);c=a.divide(f,e).multiply(c,e);" + "==binaryOperator?result=b.add(c,
e).toString():" - "==binaryOperator?result=b.subtract(c,e).toString():" * "==binaryOperator?result=c.toString():" / "==binaryOperator&&(""!=c&&0!=c||errorFlash(),result=b.divide(a.divide(f,e),e).toString());if(""!=result)return result=removeZeroes(result)}else if(" + "==binaryOperator?result=b.add(c,e).toString():" - "==binaryOperator?result=b.subtract(c,e).toString():" * "==binaryOperator?result=b.multiply(c,e).toString():" / "==binaryOperator&&(""!=c&&0!=c||errorFlash(),result=b.divide(c,e).toString()),
""!=result)return result;return""}
function enterPressed(){var a=!1;isPercent&&(lastRightSide=lastOperator="",a=!0);var b=$("#display1").val();var c=b.indexOf(" + ");if(-1!=c)var e=" + ";else c=b.indexOf(" - "),-1!=c?e=" - ":(c=b.indexOf(" * "),-1!=c?e=" * ":(c=b.indexOf(" / "),e=-1!=c?" / ":""));if(""==e)""!=lastOperator&&""==e&&(binaryOperator=lastOperator,leftSide=$("#display1").val(),rightSide=lastRightSide,b=compute());else{var f=b.substring(0,c);leftSide=f;if((f+e).length!=b.length){rightSide=b.substring(c+3,b.length);binaryOperator=
e;if(" / "==binaryOperator&&(""==rightSide||0==rightSide)){errorFlash();$("#display1").val(leftSide);dc();return}b=compute();lastOperator=binaryOperator;lastRightSide=rightSide}}c=b.substring(b.length-3,b.length);" + "!=c&&" - "!=c&&" * "!=c&&" / "!=c&&(canClear=!0);$("#display1").val(b);dc();0==nextEnterIsFake&&(a?addToHistory(leftSide+binaryOperator+rightSide+"% = "+b+"; "):addToHistory(leftSide+binaryOperator+rightSide+" = "+b+"; "));binaryOperator=""}
function revertSign(a){stripBadSymbols();var b=$("#display1").val();var c=b.indexOf(" + ");if(-1!=c)var e=" + ";else c=b.indexOf(" - "),-1!=c?e=" - ":(c=b.indexOf(" * "),-1!=c?e=" * ":(c=b.indexOf(" / "),e=-1!=c?" / ":""));if(""==e)"-"==a.value.substring(0,1)?a.value=a.value.substring(1,a.value.length):a.value="-"+a.value;else{var f=b.substring(0,c);leftSide=f;f+=e;rightSide=b.substring(c+3,b.length);rightSide="-"==rightSide.substring(0,1)?rightSide.substring(1,rightSide.length):"-"+rightSide;a.value=
f+rightSide}dc()}function backSpace(){var a=$("#display1").val();var b=a.substring(a.length-3,a.length);a=" + "==b||" - "==b||" * "==b||" / "==b?a.substring(0,a.length-3):a.substring(0,a.length-1);""==a&&(a="0");$("#display1").val(a);lastOperator="";dc()}
function unaryPreprocessor(){var a=$("#display1").val();var b=a.substring(a.length-3,a.length);if(" + "==b||" - "==b||" * "==b||" / "==b)a=a.substring(0,a.length-3);$("#display1").val(a);lastOperator="";nextEnterIsFake=!0;enterPressed();lastOperator="";nextEnterIsFake=!1;dc()}
function unaryOperationRight(a,b){if(""!=a&&""!=b){var c=$("#display1").val();var e=c.indexOf(" + ");if(-1!=e)var f=" + ";else e=c.indexOf(" - "),-1!=e?f=" - ":(e=c.indexOf(" * "),-1!=e?f=" * ":(e=c.indexOf(" / "),f=-1!=e?" / ":""));if(""!=f){var g=c.substring(0,e);leftSide=g;g+=f;c=rightSide=c.substring(e+3,c.length);if(""!=rightSide){if("percent"==a){e=new BigDecimal("100");f=new BigDecimal(rightSide);var h=new BigDecimal(leftSide),k=new MathContext(40);e=f.divide(e,k);rightSide=e.multiply(h,k).toString()}else rightSide=
computeUnary(rightSide,a,b);rightSide=removeZeroes(rightSide);$("#display1").val(g+rightSide);addToHistory(leftSide+binaryOperator+" "+a+"("+c+") = "+g+rightSide+"; ")}else"percent"!=a&&unaryOperation(a,b)}else"percent"!=a&&unaryOperation(a,b);dc()}}
function unaryOperation(a,b){if(""!=a&&""!=b){stripBadSymbols();var c;$("#display1").val();unaryPreprocessor();var e=c=$("#display1").val();c=computeUnary(c,a,b);c=removeZeroes(c);$("#display1").val(c);addToHistory(a+"("+e+") = "+c+"; ");canClear=!0;dc()}}
function computeUnary(a,b,c){if(""!=a&&""!=b&&""!=c){var e="",f=new BigDecimal(a);if(""!=c&&-1<c)var g=new BigDecimal(String(c));var h=new MathContext(40);num=parseFloat(a);Number.toFixed||(Number.prototype.toFixed=function(a){return Math.round(this*Math.pow(10,a))/Math.pow(10,a)});"sqr"==b?e=f.multiply(f,h).toString():"sqrt"==b?e=Math.sqrt(a):"rt3"==b?e=nRroot(a,3):"cube"==b?e=f.multiply(f,h).multiply(f,h).toString():"rtN"==b?e=nRroot(a,c):"powN"==b?e=f.pow(g,h).toString():"random"==b?e=0==a?Math.random():
Math.random()*a:"roundXX"==b?e=roundNum(a,2):"int"==b?e=Math.round(a):"roundN"==b?e=roundNum(a,c):"sin"==b?(isDegrees&&(num=3.14159265359*num/180),e=num.sin().toFixed(11)):"cos"==b?(isDegrees&&(num=3.14159265359*num/180),e=num.cos().toFixed(11)):"tan"==b?(isDegrees&&(num=3.14159265359*num/180),e=num.tan().toFixed(11)):"cot"==b?(isDegrees&&(num=3.14159265359*num/180),e=num.cot().toFixed(11)):"asin"==b?(e=num.asin().toFixed(11),isDegrees&&(e*=180/Math.PI)):"acos"==b?(e=num.acos().toFixed(11),isDegrees&&
(e*=180/Math.PI)):"atan"==b?(e=num.atan().toFixed(11),isDegrees&&(e*=180/Math.PI)):"sinh"==b?(isDegrees&&(num=3.14159265359*num/180),e=num.sinh().toFixed(11)):"cosh"==b?(isDegrees&&(num=3.14159265359*num/180),e=num.cosh().toFixed(11)):"tanh"==b?(isDegrees&&(num=3.14159265359*num/180),e=num.tanh().toFixed(11)):"coth"==b?(isDegrees&&(num=3.14159265359*num/180),e=num.coth().toFixed(11)):"acot"==b?(e=num.acot().toFixed(11),isDegrees&&(e*=180/Math.PI)):"sec"==b?(isDegrees&&(num=3.14159265359*num/180),
e=num.sec().toFixed(11)):"asec"==b?(e=num.asec().toFixed(11),isDegrees&&(e*=180/Math.PI)):"sech"==b?(isDegrees&&(num=3.14159265359*num/180),e=num.sech().toFixed(11)):"exp"==b?e=num.exp().toFixed(11):"ln"==b?e=num.ln().toFixed(11):"logN"==b?e=num.log(c).toFixed(11):"log10"==b&&(e=num.log10().toFixed(11));return e}}
function nRroot(a,b){try{var c=1==b%2&&0>a;c&&(a=-a);var e=Math.pow(a,1/b);b=Math.pow(e,b);if(1>Math.abs(a-b)&&0<a==0<b)var f=c?-e:e;""!=f&&"undefined"!=f||"NaN"==f;return f}catch(g){return"NaN"}}function ln(a){a.display.value=Math.log(a.display.value)}function exp(a){a.display.value=Math.exp(a.display.value)}function sqrt(a){a.display.value=Math.sqrt(a.display.value)}function backSpace3(){var a=$("#display3").val();a=a.substring(0,a.length-1);""==a&&(a="0");$("#display3").val(a);canClear=!1}
function clearAll2(){$("#display3").val("")}function revertSign2(){var a=$("#display3").val();a="-"==a.substring(0,1)?a.substring(1,a.length):"-"+a;$("#display3").val(a)}function addDigit2(a){var b=$("#display3").val();b+=a;$("#display3").val(b)}function complexOperation(){var a=$("#display3").val();""!=complexOp&&(1==complexIsRight?unaryOperationRight(complexOp,a):unaryOperation(complexOp,a));canClear=!0;clearAll2();$("#question").hide();$("#calculator").show()}
function roundNum(a,b){var c=Math.pow(10,b);return Math.round(a*c)/c}function pi(){var a=$("#display1").val();0==a&&(a="");1==canClear&&(a="");a+=Math.PI;$("#display1").val(a);dc()}function eNum(){var a=$("#display1").val();0==a&&(a="");1==canClear&&(a="");a+=Math.E;$("#display1").val(a);dc()}Number.prototype.abs=function(){return Math.abs(this)};Number.prototype.acos=function(){return Math.acos(this)};Number.prototype.acosec=function(){return Math.asin(1/this)};
Number.prototype.acosech=function(){return 0>this?Math.log((1-Math.sqrt(1+this*this))/this):Math.log((1+Math.sqrt(1+this*this))/this)};Number.prototype.acosh=function(){return Math.log(this+Math.sqrt(this*this-1))};Number.prototype.acot=function(){return Math.PI/2-Math.atan(this)};Number.prototype.acoth=function(){return Math.log((this+1)/(this-1))/2};Number.prototype.asec=function(){return Math.PI/2-Math.asin(1/this)};Number.prototype.asech=function(){return Math.log((1+Math.sqrt(1-this*this))/this)};
Number.prototype.asin=function(){return Math.asin(this)};Number.prototype.asinh=function(){return Math.log(this+Math.sqrt(this*this+1))};Number.prototype.atan=function(){return Math.atan(this)};Number.prototype.atanh=function(){return Math.log((1+this)/(1-this))/2};Number.prototype.ceil=function(){return Math.ceil(this)};Number.prototype.cos=function(){return Math.cos(this)};Number.prototype.cosec=function(){return 1/Math.sin(this)};Number.prototype.cosech=function(){return 2/(Math.exp(this)-Math.exp(-this))};
Number.prototype.cosh=function(){return(Math.exp(this)+Math.exp(-this))/2};Number.prototype.cot=function(){return 1/Math.tan(this)};Number.prototype.coth=function(){return(Math.exp(this)+Math.exp(-this))/(Math.exp(this)-Math.exp(-this))};Number.prototype.degToRad=function(){return this*Math.PI/180};Number.prototype.exp=function(){return Math.exp(this)};Number.prototype.floor=function(){return Math.floor(this)};Number.prototype.isInRange=function(a,b){return this>=a&&this<=b};
Number.prototype.limit=function(a,b){return this<a?a:this>b?b:this};Number.prototype.limitAbove=function(a){return Math.min(a,this)};Number.prototype.limitBelow=function(a){return Math.max(a,this)};Number.prototype.ln=function(){return Math.log(this)};Number.prototype.log=function(a){return Math.log(this)/Math.log(a)};Number.prototype.log2=function(){return Math.log(this)/Math.LN2};Number.prototype.log10=function(){return Math.log(this)/Math.LN10};
Number.prototype.mod=function(a){return 0<=this?this%a:(this%a+Math.abs(a))%a};Number.prototype.radToDeg=function(){return 180*this/Math.PI};Number.prototype.round=function(){return Math.round(this)};Number.prototype.sec=function(){return 1/Math.cos(this)};Number.prototype.sech=function(){return 2/(Math.exp(this)+Math.exp(-this))};Number.prototype.sign=function(){return 0==this?0:0<this?1:-1};Number.prototype.sin=function(){return Math.sin(this)};
Number.prototype.sinh=function(){return(Math.exp(this)-Math.exp(-this))/2};Number.prototype.sqrt=function(){return Math.sqrt(this)};Number.prototype.pow=function(a){return Math.pow(this,a)};Number.prototype.tan=function(){return Math.tan(this)};Number.prototype.tanh=function(){return(Math.exp(this)-Math.exp(-this))/(Math.exp(this)+Math.exp(-this))};Number.prototype.wrap=function(a,b){return a+(this-a).mod(b-a)};