function disableEnterKey(a){return 13!=(window.event?window.event.keyCode:a.which)}var ctrlDown=!1,ctrlKey=17,vKey=86,cKey=67;
$(document).keydown(function(a){var b=document.getElementById("form1");if(0==$("#display123").is(":visible")){if(1==$("#display3").is(":visible")){if("49"==a.keyCode||"97"==a.keyCode)addDigit2("1"),a.preventDefault();if("50"==a.keyCode||"98"==a.keyCode)addDigit2("2"),a.preventDefault();if("51"==a.keyCode||"99"==a.keyCode)addDigit2("3"),a.preventDefault();if("52"==a.keyCode||"100"==a.keyCode)addDigit2("4"),a.preventDefault();if("53"==a.keyCode||"101"==a.keyCode)addDigit2("5"),a.preventDefault();if("54"==
a.keyCode||"102"==a.keyCode)addDigit2("6"),a.preventDefault();if("55"==a.keyCode||"103"==a.keyCode)addDigit2("7"),a.preventDefault();if("56"==a.keyCode||"104"==a.keyCode)addDigit2("8"),a.preventDefault();if("57"==a.keyCode||"105"==a.keyCode)addDigit2("9"),a.preventDefault();if("48"==a.keyCode||"96"==a.keyCode)addDigit2("0"),a.preventDefault();"110"==a.keyCode&&(addDigit2("."),a.preventDefault());"190"==a.keyCode&&(addDigit2("."),a.preventDefault());"13"==a.keyCode&&(canClear=!0,complexOperation(),
a.preventDefault());"8"==a.keyCode&&(backSpace3(),a.preventDefault());"27"==a.keyCode&&(clearAll2(b.display),$("#question").hide(),$("#calculator").show(),a.preventDefault());"67"!=a.keyCode||ctrlDown||a.metaKey||(clearAll2(b.display),a.preventDefault());"192"==a.keyCode&&(revertSign2(),a.preventDefault())}}else{if("49"==a.keyCode||"97"==a.keyCode)addDigit(b.display,"1"),a.preventDefault();if("50"==a.keyCode||"98"==a.keyCode)addDigit(b.display,"2"),a.preventDefault();if("51"==a.keyCode||"99"==a.keyCode)addDigit(b.display,
"3"),a.preventDefault();if("52"==a.keyCode||"100"==a.keyCode)addDigit(b.display,"4"),a.preventDefault();if("53"==a.keyCode&&!a.shiftKey||"101"==a.keyCode)addDigit(b.display,"5"),a.preventDefault();"53"==a.keyCode&&a.shiftKey&&(calcPercent("*"),a.preventDefault());if("54"==a.keyCode||"102"==a.keyCode)addDigit(b.display,"6"),a.preventDefault();if("55"==a.keyCode||"103"==a.keyCode)addDigit(b.display,"7"),a.preventDefault();if("56"==a.keyCode||"104"==a.keyCode)addDigit(b.display,"8"),a.preventDefault();
if("57"==a.keyCode||"105"==a.keyCode)addDigit(b.display,"9"),a.preventDefault();if("48"==a.keyCode||"96"==a.keyCode)addDigit(b.display,"0"),a.preventDefault();"110"==a.keyCode&&(addDigit(b.display,"."),a.preventDefault());"190"==a.keyCode&&(addDigit(b.display,"."),a.preventDefault());"111"==a.keyCode&&(addNow("/"),a.preventDefault());"191"==a.keyCode&&(addNow("/"),a.preventDefault());"107"==a.keyCode&&(addNow("+"),a.preventDefault());"187"==a.keyCode&&(addNow("+"),a.preventDefault());"109"==a.keyCode&&
(addNow("-"),a.preventDefault());"189"==a.keyCode&&(addNow("-"),a.preventDefault());"106"==a.keyCode&&(addNow("*"),a.preventDefault());"88"==a.keyCode&&(addNow("*"),a.preventDefault());"13"==a.keyCode&&(canClear=!0,enterPressed(),a.preventDefault());"8"==a.keyCode&&(backSpace(),a.preventDefault());"27"==a.keyCode&&(clearAll(b.display),a.preventDefault());"67"!=a.keyCode||ctrlDown||a.metaKey||(clearAll(b.display),a.preventDefault());"192"==a.keyCode&&(revertSign(b.display),a.preventDefault())}dc()});
$(document).keydown(function(a){a.keyCode==ctrlKey&&(ctrlDown=!0)}).keyup(function(a){a.keyCode==ctrlKey&&(ctrlDown=!1)});$(document).keydown(function(a){(ctrlDown||a.metaKey)&&a.keyCode==vKey&&pasteFromClipboard();(ctrlDown||a.metaKey)&&a.keyCode==cKey&&copyToClipboard();dc()});
function clickHandler(a){"k1"==a.srcElement.name?addDigit(document.getElementById("display1"),"1"):"k2"==a.srcElement.name?addDigit(document.getElementById("display1"),"2"):"k3"==a.srcElement.name?addDigit(document.getElementById("display1"),"3"):"k4"==a.srcElement.name?addDigit(document.getElementById("display1"),"4"):"k5"==a.srcElement.name?addDigit(document.getElementById("display1"),"5"):"k6"==a.srcElement.name?addDigit(document.getElementById("display1"),"6"):"k7"==a.srcElement.name?addDigit(document.getElementById("display1"),
"7"):"k8"==a.srcElement.name?addDigit(document.getElementById("display1"),"8"):"k9"==a.srcElement.name?addDigit(document.getElementById("display1"),"9"):"k0"==a.srcElement.name?addDigit(document.getElementById("display1"),"0"):"cbPst"==a.srcElement.name?pasteFromClipboard():"cbCpy"==a.srcElement.name?copyToClipboard():"cbPrct"==a.srcElement.name?calcPercent():"cbPrct2"==a.srcElement.name?calcPercent2():"kChange"==a.srcElement.name?revertSign(document.getElementById("display1")):"kEnter"==a.srcElement.name?
enterPressed():"kPlus"==a.srcElement.name?addNow("+"):"kMinus"==a.srcElement.name?addNow("-"):"kTimes"==a.srcElement.name?addNow("*"):"kDiv"==a.srcElement.name?addNow("/"):"kMC"==a.srcElement.name?memClear():"kMPlus"==a.srcElement.name?memPlus(!1):"kMMinus"==a.srcElement.name?memPlus(!0):"kMR"==a.srcElement.name?memoryRecall():"kBkSpc"==a.srcElement.name?backSpace():"kDxx"==a.srcElement.name?unaryOperationRight("roundXX"):"kInt"==a.srcElement.name?unaryOperationRight("int"):"kCmRand"==a.srcElement.name?
(complexOp="roundN",complexIsRight=!0,$("#calculator").hide(),$("#question").show(),$.mobile.changePage($("#question"),{transition:"none"},!1,!0)):"kEsc"==a.srcElement.name?clearAll(this.form.display):"kESCTop"==a.srcElement.name?clearAll(this.form.display):"kBtnSqrt"==a.srcElement.name?unaryOperationRight("sqrt",2):"kBtnSin"==a.srcElement.name?unaryOperationRight("sin",2):"kBtnSinH"==a.srcElement.name?unaryOperationRight("sinh"):"kBtnAsin"==a.srcElement.name?unaryOperationRight("asin"):"kBtnLn"==
a.srcElement.name?unaryOperationRight("ln"):"kBtnCube"==a.srcElement.name?unaryOperationRight("rt3",3):"kBtnCos"==a.srcElement.name?unaryOperationRight("cos",3):"kBtnCosH"==a.srcElement.name?unaryOperationRight("cosh",3):"kBtnACos"==a.srcElement.name?unaryOperationRight("acos",3):"kBtnLogTen"==a.srcElement.name?unaryOperationRight("log10"):"kBtnNsq"==a.srcElement.name?(complexOp="rtN",complexIsRight=!0,$("#calculator").hide(),$("#question").show(),$.mobile.changePage($("#question"),{transition:"none"},
!1,!0)):"kBtnTan"==a.srcElement.name?unaryOperationRight("tan",3):"kBtnTanH"==a.srcElement.name?unaryOperationRight("tanh",3):"kBtnAtan"==a.srcElement.name?unaryOperationRight("atan",3):"kBtnLOGn"==a.srcElement.name?(complexOp="logN",complexIsRight=!0,$("#calculator").hide(),$("#question").show(),$.mobile.changePage($("#question"),{transition:"none"},!1,!0)):"kBtnSquare"==a.srcElement.name?unaryOperationRight("sqr"):"kBtnCot"==a.srcElement.name?unaryOperationRight("cot",3):"kBtnCotN"==a.srcElement.name?
unaryOperationRight("coth",3):"kBtnACot"==a.srcElement.name?unaryOperationRight("acot",3):"kBtnPI"==a.srcElement.name?pi():"kBtCmCube"==a.srcElement.name?unaryOperationRight("cube"):"kBtCmSec"==a.srcElement.name?unaryOperationRight("sec",1):"kBtCmSecH"==a.srcElement.name?unaryOperationRight("sech",1):"kBtCmASec"==a.srcElement.name?unaryOperationRight("asec",1):"kBtnCmdE"==a.srcElement.name?eNum():"kUglyButton"==a.srcElement.name?(complexOp="powN",complexIsRight=!0,$("#calculator").hide(),$("#question").show(),
$.mobile.changePage($("#question"),{transition:"none"},!1,!0)):"kBtnRad"==a.srcElement.name?(isDegrees=!1,f()):"kBtnDeg"==a.srcElement.name?(isDegrees=!0,f()):"kbEXP"==a.srcElement.name?unaryOperationRight("exp",1):"kbRNDbtn"==a.srcElement.name?unaryOperationRight("random"):"kbClrSecScr"==a.srcElement.name?clearAll2():"kbBackSecScr"==a.srcElement.name?backSpace3():"kbs7"==a.srcElement.name?addDigit2("7"):"kbs8"==a.srcElement.name?addDigit2("8"):"kbs9"==a.srcElement.name?addDigit2("9"):"kbs4"==a.srcElement.name?
addDigit2("4"):"kbs5"==a.srcElement.name?addDigit2("5"):"kbs6"==a.srcElement.name?addDigit2("6"):"kbs1"==a.srcElement.name?addDigit2("1"):"kbs2"==a.srcElement.name?addDigit2("2"):"kbs3"==a.srcElement.name?addDigit2("3"):"kbsZero"==a.srcElement.name?addDigit2("0"):"kbsCncl"==a.srcElement.name?($("#question").hide(),$("#calculator").show()):"enter2"==a.srcElement.name?complexOperation():"dotPoint"==a.srcElement.name?addDigit2("."):"kDot"==a.srcElement.name?addDigit(document.getElementById("display1"),
"."):"revert2"==a.srcElement.name&&revertSign2(document.getElementById("display123"))}
document.addEventListener("DOMContentLoaded",function(){document.getElementById("kbClrSecScr").addEventListener("click",clickHandler);document.getElementById("dotPoint").addEventListener("click",clickHandler);document.getElementById("kDot").addEventListener("click",clickHandler);document.getElementById("kbsCncl").addEventListener("click",clickHandler);document.getElementById("enter2").addEventListener("click",clickHandler);document.getElementById("kbs7").addEventListener("click",clickHandler);document.getElementById("kbs8").addEventListener("click",
clickHandler);document.getElementById("kbs9").addEventListener("click",clickHandler);document.getElementById("kbs4").addEventListener("click",clickHandler);document.getElementById("kbs5").addEventListener("click",clickHandler);document.getElementById("kbs6").addEventListener("click",clickHandler);document.getElementById("kbs1").addEventListener("click",clickHandler);document.getElementById("kbs2").addEventListener("click",clickHandler);document.getElementById("kbs3").addEventListener("click",clickHandler);
document.getElementById("kbsZero").addEventListener("click",clickHandler);document.getElementById("kbBackSecScr").addEventListener("click",clickHandler);document.getElementById("kbEXP").addEventListener("click",clickHandler);document.getElementById("kbRNDbtn").addEventListener("click",clickHandler);document.getElementById("kBtnSquare").addEventListener("click",clickHandler);document.getElementById("btnRad").addEventListener("click",clickHandler);document.getElementById("btnDeg").addEventListener("click",
clickHandler);document.getElementById("kUglyButton").addEventListener("click",clickHandler);document.getElementById("kBtnCmdE").addEventListener("click",clickHandler);document.getElementById("kBtCmSec").addEventListener("click",clickHandler);document.getElementById("kBtCmASec").addEventListener("click",clickHandler);document.getElementById("kBtCmSecH").addEventListener("click",clickHandler);document.getElementById("kBtnCot").addEventListener("click",clickHandler);document.getElementById("kBtCmCube").addEventListener("click",
clickHandler);document.getElementById("kBtnPI").addEventListener("click",clickHandler);document.getElementById("kBtnACot").addEventListener("click",clickHandler);document.getElementById("kBtnCotN").addEventListener("click",clickHandler);document.getElementById("kBtnLOGn").addEventListener("click",clickHandler);document.getElementById("kBtnNsq").addEventListener("click",clickHandler);document.getElementById("kBtnTan").addEventListener("click",clickHandler);document.getElementById("kBtnAtan").addEventListener("click",
clickHandler);document.getElementById("kBtnTanH").addEventListener("click",clickHandler);document.getElementById("kBtnCube").addEventListener("click",clickHandler);document.getElementById("kBtnLogTen").addEventListener("click",clickHandler);document.getElementById("kBtnCos").addEventListener("click",clickHandler);document.getElementById("kBtnCosH").addEventListener("click",clickHandler);document.getElementById("kBtnACos").addEventListener("click",clickHandler);document.getElementById("kBtnSqrt").addEventListener("click",
clickHandler);document.getElementById("kBtnSin").addEventListener("click",clickHandler);document.getElementById("kBtnSinH").addEventListener("click",clickHandler);document.getElementById("kBtnAsin").addEventListener("click",clickHandler);document.getElementById("kBtnLn").addEventListener("click",clickHandler);document.getElementById("k1").addEventListener("click",clickHandler);document.getElementById("k2").addEventListener("click",clickHandler);document.getElementById("k3").addEventListener("click",
clickHandler);document.getElementById("k4").addEventListener("click",clickHandler);document.getElementById("k5").addEventListener("click",clickHandler);document.getElementById("k6").addEventListener("click",clickHandler);document.getElementById("k7").addEventListener("click",clickHandler);document.getElementById("k8").addEventListener("click",clickHandler);document.getElementById("k9").addEventListener("click",clickHandler);document.getElementById("k0").addEventListener("click",clickHandler);document.getElementById("cbCpy").addEventListener("click",
clickHandler);document.getElementById("cbPst").addEventListener("click",clickHandler);document.getElementById("cbPrct").addEventListener("click",clickHandler);document.getElementById("cbPrct2").addEventListener("click",clickHandler);document.getElementById("kChange").addEventListener("click",clickHandler);document.getElementById("revert2").addEventListener("click",clickHandler);document.getElementById("enter").addEventListener("click",clickHandler);document.getElementById("plus").addEventListener("click",
clickHandler);document.getElementById("kMinus").addEventListener("click",clickHandler);document.getElementById("kTimes").addEventListener("click",clickHandler);document.getElementById("kDiv").addEventListener("click",clickHandler);document.getElementById("kMC").addEventListener("click",clickHandler);document.getElementById("kMPlus").addEventListener("click",clickHandler);document.getElementById("kMMinus").addEventListener("click",clickHandler);document.getElementById("kMR").addEventListener("click",
clickHandler);document.getElementById("kBkSpc").addEventListener("click",clickHandler);document.getElementById("kDxx").addEventListener("click",clickHandler);document.getElementById("kInt").addEventListener("click",clickHandler);document.getElementById("kCmRand").addEventListener("click",clickHandler);document.getElementById("kEsc").addEventListener("click",clickHandler);document.getElementById("kESCTop").addEventListener("click",clickHandler);setFullScreen();isDegrees="true"==localStorage.deg_selected;
"undefined"==typeof isDegrees&&(isDegrees=!1);1==isDegrees?($("#btnRad").button("enable"),$("#btnRad").button("refresh"),$("#btnDeg").button("disable")):($("#btnRad").button("disable"),$("#btnRad").button("refresh"),$("#btnDeg").button("enable"));$("#btnDeg").button("refresh")});